export const ADD_EVENT = 'ADD_EVENT';
export const CHOOSE_EVENTS_TEMPLATE = 'CHOOSE_EVENTS_TEMPLATE';
export const ADD_EVENT_TEMPLATE = 'ADD_EVENT_TEMPLATE';
export const ADD_PATIENT = 'ADD_PATIENT';
